# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d5107eb67fd7d9101d4b17aac7520024"
name = "sustainable-equity-app"
handle = "sustainable-equity-app-7"
application_url = "https://such-pricing-social-rebates.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://such-pricing-social-rebates.trycloudflare.com/auth/callback",
  "https://such-pricing-social-rebates.trycloudflare.com/auth/shopify/callback",
  "https://such-pricing-social-rebates.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
