api_version = "2025-04"
[[extensions]]
name = "t:name"
handle = "admin-product-details"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/ProductDetailsExtension.jsx"
target = "admin.product-details.action.render"

# Valid extension targets:
# Product details page
# - admin.product-details.action.render 